from pathlib import Path
from datetime import datetime
from config import config
from theme import get_theme_name
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet


EXPORT_FOLDER = Path("exports")

def ensure_export_folder():
    EXPORT_FOLDER.mkdir(exist_ok=True)


def generate_filename(extension: str) -> Path:
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    return EXPORT_FOLDER / f"conversation_{timestamp}.{extension}"


def export_markdown(history):
    
    ensure_export_folder()

    file_path = generate_filename("md")

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    with open(file_path, "w", encoding="utf-8") as file:

        file.write("# PocketAI Conversation\n\n")

        file.write(f"Generated by PocketAI {config['version']}\n\n")

        file.write(f"**Date:** {now}\n\n")

        file.write(f"**Model:** {config['model']}\n\n")

        file.write(f"**Theme:** {get_theme_name()}\n\n")

        file.write("---\n\n")

        for message in history:

            role = message["role"].capitalize()

            content = message["content"]

            file.write(f"## {role}\n\n")

            file.write(content)

            file.write("\n\n")

    return file_path

def export_text(history):
    ensure_export_folder()

    file_path = generate_filename("txt")

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    with open(file_path, "w", encoding="utf-8") as file:

        file.write("PocketAI Conversation\n")
        file.write("=" * 60 + "\n\n")

        file.write(f"Generated by PocketAI {config['version']}\n")
        file.write(f"Date: {now}\n")
        file.write(f"Model: {config['model']}\n")
        file.write(f"Theme: {get_theme_name()}\n")

        file.write("\n")
        file.write("=" * 60)
        file.write("\n\n")

        for message in history:

            role = message["role"].upper()

            file.write(f"{role}\n")
            file.write("-" * len(role))
            file.write("\n")

            file.write(message["content"])

            file.write("\n\n")

    return file_path

def export_pdf(history):
    ensure_export_folder()

    file_path = generate_filename("pdf")

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(str(file_path))

    elements = []

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    elements.append(Paragraph("<b>PocketAI Conversation</b>", styles["Title"]))

    elements.append(Paragraph(f"Generated by PocketAI {config['version']}", styles["Normal"]))
    elements.append(Paragraph(f"Date: {now}", styles["Normal"]))
    elements.append(Paragraph(f"Model: {config['model']}", styles["Normal"]))
    elements.append(Paragraph(f"Theme: {get_theme_name()}", styles["Normal"]))
    elements.append(Paragraph("<br/><br/>", styles["Normal"]))

    for message in history:

        role = message["role"].capitalize()

        content = message["content"].replace("\n", "<br/>")

        elements.append(Paragraph(f"<b>{role}</b>", styles["Heading2"]))
        elements.append(Paragraph(content, styles["Normal"]))
        elements.append(Paragraph("<br/>", styles["Normal"]))

    pdf.build(elements)

    return file_path